export const expenseCategories = {
  utlities: {
    thisCategoryTitle: "Utlities & Bills",
    electricity: "Electricity",
    water: "Water",
    mobile: "Mobile",
    internet: "Internet",
    tv: "TV",
    gas: "Gas",
    cc: "Credit Card",
    repair: "Service & Repairs",
    rent: "Rent",
  },
  travel: {
    thisCategoryTitle: "Transportation",
    fuel: "Fuel",
    parking: "Parking Fees",
    taxi: "Taxi",
    train: "Train",
    bus: "Bus",
    aeroplan: "Aeroplan",
    toll: "Toll",
  },
  food: {
    thisCategoryTitle: "Food & Drinks",
    groceries: "Groceries",
    rest: "Restaurant",
    cafe: "Cafe",
    order: "Ordering Online",
    snack: "Snacks",
    drink: "Drinks",
    pet: "Pet Food",
  },
  shop: {
    thisCategoryTitle: "Shopping",
    cloth: "Clothing",
    gadget: "Gadgets",
    appliance: "Home Appliances",
    furni: "Furniture",
    foot: "Footware",
    acc: "Accessories",
    tool: "Tools",
    cleaning: "Cleaning Supplies",
    toilet: "Toiletries",
  },
  health: {
    thisCategoryTitle: "Medical & Healthcare",
    visit: "Doctor Visits",
    meds: "Medicines",
    checkup: "Health Checkup",
    vaccni: "Vaccination",
    operation: "Operation & Surgery",
  },
  loan: {
    thisCategoryTitle: "Loans & Debts",
    bank: "Bank",
    mortage: "Mortgage",
    debttaken: "Debt Taken",
    debtgiven: "Debt Given",
    emi: "EMI",
    default: "Default",
  },
  edu: {
    thisCategoryTitle: "Education",
    school: "School Fees",
    college: "College Fees",
    course: "Course Fees",
    coaching: "Tuition/Coaching Classes",
    online: "Online Learning Subscriptions",
    supplies: "Educational Supplies",
  },
  gift: {
    thisCategoryTitle: "Gifting & Charity",
    bday: "Birthday",
    wed: "Wedding",
    anna: "Anniversary",
    festiv: "Festival",
    special: "Special Occasions",
    gen: "General",
    donation: "Donation",
  },
  ent: {
    thisCategoryTitle: "Entertainment",
    movie: "Movies",
    games: "Games",
    event: "Events",
    hotel: "Hotel Stay",
    sub: "Subscriptions",
    park: "Amusement Parks/Zoos",
    hobbie: "Hobbies",
  },
  personal: {
    thisCategoryTitle: "Personal Care",
    salon: "Salon",
    gym: "GYM/Fitness",
    cos: "Cosmetics",
    eqp: "Fitness Equipment",
    yoga: "Yoga",
    wellness: "Wellness",
  },
  tax: {
    thisCategoryTitle: "Taxation",
    tax: "Tax",
  },
  insurance: {
    thisCategoryTitle: "Insurance",
    insurance: "Insurance",
  },
  misc: {
    thisCategoryTitle: "Miscellaneous Expenses",
    misc: "Miscellaneous",
  },
};

export const incomeCategories = {
  income: {
    thisCategoryTitle: "Income",
  },
};

export const incomeSubCat = [
  "Salary",
  "Salary Bonus",
  "Part-Time Job",
  "Freelance Work",
  "Reselling",
  "Rental Income",
  "Service Provided",
  "Loan Repaid",
  "Prize Money",
  "Loan Taken",
];
